feat: support modular import in development mode
meowtec/vite-plugin-import pull request #4
Opened 2021-02-24 06:33 UTC by robert0609

支持在开发模式下的按需加载

2021-02-24 12:08 UTC, meowtec commented
不要改成总是按需加载，vite 在开发模式下 import 子模块容易出问题。

可以作为一个配置项放在 ImportPluginOptions 中：

```diff
export type ImportPluginOptions = Array<{
  [key: string]: any;
  libraryName: string;
  libraryDirectory?: string;
  camel2DashComponentName?: boolean;
+ onlyBuild: true, // 默认只在 build 模式下开启
}>;
```

```
const plugins = options.map(...).filter(Boolean) // 在 map 内判断是否需要引入 babel-plugin-import
```

2021-02-25 03:07 UTC, robert0609 commented
> 不要改成总是按需加载，vite 在开发模式下 import 子模块容易出问题。
> 
> 可以作为一个配置项放在 ImportPluginOptions 中：
> 
> ```diff
> export type ImportPluginOptions = Array<{
>   [key: string]: any;
>   libraryName: string;
>   libraryDirectory?: string;
>   camel2DashComponentName?: boolean;
> + onlyBuild: true, // 默认只在 build 模式下开启
> }>;
> ```
> 
> ```
> const plugins = options.map(...).filter(Boolean) // 在 map 内判断是否需要引入 babel-plugin-import
> ```
“vite 在开发模式下 import 子模块容易出问题”，请教一下会出什么问题呢？

2021-02-25 05:45 UTC, meowtec commented
@robert0609 旧版本的 Vite 如果需要引入子路径，需要手动把子路径添加到 optimizeDeps 里面，否则会出问题。

但是我试了下最新版本的 Vite，好像能根据 import 的路径自动 optimize 了，但是也是存在一些缺陷的：它只会在解析到 import 子路径后才会去做 optimize，而 optimize 的过程是异步的，完成之后页面会刷新。

所以会导致奇怪的行为：
第一次启动，打开页面后，页面会刷新几次。
执行操作，比如打开弹窗之类的，用到了某个新的（首屏渲染没用到的）子模块，页面也会刷新。

2021-02-25 06:36 UTC, robert0609 commented
好，多谢。我明白了，这个我加一个选项来控制一下

2021-02-26 03:20 UTC, meowtec approved these changes

2021-02-26 03:20 UTC, meowtec commented on src/index.ts
> +    onlyBuild = options.onlyBuild === false ? false : true;
onlyBuild = options.onlyBuild !== false

2021-02-26 03:20 UTC, meowtec commented on src/index.ts
> +  let babelImportPluginOptions: BabelImportPluginOptions = [];
这个用法有一个缺点：要么都 onlyBuild = true, 要么 都 onlyBuild = false。

我之前的想法是把 onlyBuild 放在和 camel2DashComponentName 同级的地方，然后 map 出 plugins 的时候，根据 `isBuild` 和 每一项的 `onlyBuild / codeIncludesLibraryName` 进行过滤。

```javascript
plugins: options.filter(({ libraryName, onlyBuild }) => (isBuild || !onlyBuild) && code.includes(libraryName)).map(...),

if (!plugins.length) return
```

2021-02-26 03:23 UTC, meowtec requested changes

2021-02-26 03:23 UTC, meowtec commented on src/index.ts
> +  let babelImportPluginOptions: BabelImportPluginOptions = [];
这个用法有一个缺点：要么都 onlyBuild = true, 要么 都 onlyBuild = false。

我之前的想法是把 onlyBuild 放在和 camel2DashComponentName 同级的地方，然后 map 出 plugins 的时候，根据 `isBuild` 和 每一项的 `onlyBuild / codeIncludesLibraryName` 进行过滤。

```javascript
plugins: options.filter(({ libraryName, onlyBuild }) => (isBuild || !onlyBuild) && code.includes(libraryName)).map(...),

if (!plugins.length) return
```

2021-02-26 03:23 UTC, meowtec commented on src/index.ts
> +    onlyBuild = options.onlyBuild === false ? false : true;
onlyBuild = options.onlyBuild  !== false

2021-02-26 03:41 UTC, robert0609 commented on src/index.ts
> +  let babelImportPluginOptions: BabelImportPluginOptions = [];
是的，不过我之前的考虑是既然vite开发模式下按需加载可能会有问题，那在开发模式下比较频繁的是切换整体的按需加载的开关，要么整体不开启，要么整体开启。针对每一个类库单独设置的场景使用会比较少，因此设置了整体的一个选项开关。后期如果有针对更细粒度的控制，我觉得可以再加上

2021-02-26 03:42 UTC, robert0609 commented on src/index.ts
> +    onlyBuild = options.onlyBuild === false ? false : true;
OK，这个可以优化一下

2021-02-26 03:46 UTC, robert0609 commented on src/index.ts
> +  let babelImportPluginOptions: BabelImportPluginOptions = [];
否则一旦配置的按需加载的库过多，onlyBuild的配置也会非常多，比较麻烦

2021-02-26 08:05 UTC, meowtec commented on src/index.ts
> +  let babelImportPluginOptions: BabelImportPluginOptions = [];
嗯，有道理

2021-02-26 08:06 UTC, merged

2021-02-26 08:17 UTC, meowtec commented
release v0.3.0